[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojofix"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "mojo -I src test/test_simplefix_compat.mojo"

[dependencies]
mojo = ">=0.26.1.0.dev2025122805,<0.27"
